# Generated by Django 2.0.7 on 2018-07-27 04:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='meals/image/'),
        ),
    ]
