# Generated by Django 2.0.7 on 2018-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
    ]
