# Generated by Django 2.0.7 on 2018-07-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_remove_meal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='quantity',
        ),
    ]
