# Generated by Django 2.0.7 on 2018-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_remove_meal_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
