# Generated by Django 2.0.7 on 2018-07-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180729_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.CartItems'),
            preserve_default=False,
        ),
    ]
