# Generated by Django 2.0.7 on 2018-07-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180729_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='meals',
        ),
    ]
